export const ADD_TODO = 'ADD_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const EDIT_TODO = 'EDIT_TODO'
export const SET_TITLE = 'SET_TITLE'
export const SET_TODO = 'SET_TODO'
export const SET_EDIT = 'SET_EDIT'
export const SET_ERROR = 'SET_ERROR'